### ISSUE TITLE
В случае исключительной ситуации файл не будет закрыт

### ISSUE THREAD

**Issue by kuritsynk** [Tatiana1641/laba2#2]
https://github.com/Tatiana1641/laba2/blob/c6b8cfaa09b6c668a58e6b02bbe036215c7b6f4a/main.cpp#L37

**Comment by Tatiana1641** [comment]
> [laba2/main.cpp](https://github.com/Tatiana1641/laba2/blob/c6b8cfaa09b6c668a58e6b02bbe036215c7b6f4a/main.cpp#L37)
> 
> Line 37 in [c6b8cfa](/Tatiana1641/laba2/commit/c6b8cfaa09b6c668a58e6b02bbe036215c7b6f4a)
> 
>  in.close();//закрываем файл
